// <auto-generated />
using System;
using ApiMatematicas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiMatematicas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251030030034_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiMatematicas.Models.ReinicioContrasenaToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("reiniciocontraseñas");
                });

            modelBuilder.Entity("ApiMatematicas.Models.SistemaRacha", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("actual")
                        .HasColumnType("integer")
                        .HasColumnName("actual");

                    b.Property<DateTime>("fechaUltimaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechaultimaactualizacion");

                    b.Property<DateTime?>("inicioRachaActual")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("iniciorachaactual");

                    b.Property<int>("maxima")
                        .HasColumnType("integer")
                        .HasColumnName("maxima");

                    b.Property<int>("modo")
                        .HasColumnType("integer")
                        .HasColumnName("modo");

                    b.Property<int>("usuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuarioid");

                    b.HasKey("id");

                    b.HasIndex("usuarioId");

                    b.ToTable("rachas");
                });

            modelBuilder.Entity("ApiMatematicas.Models.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("Correo")
                        .HasColumnType("text")
                        .HasColumnName("correo");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passwordhash");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("contrasena")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contrasena");

                    b.Property<DateTime>("fechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecharegistro");

                    b.Property<string>("nombreUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombreusuario");

                    b.Property<string>("rol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rol");

                    b.HasKey("id");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("ApiMatematicas.Models.ReinicioContrasenaToken", b =>
                {
                    b.HasOne("ApiMatematicas.Models.Usuario", "User")
                        .WithMany("ReinicioContraseñas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApiMatematicas.Models.SistemaRacha", b =>
                {
                    b.HasOne("ApiMatematicas.Models.Usuario", "usuario")
                        .WithMany("Rachas")
                        .HasForeignKey("usuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("ApiMatematicas.Models.Usuario", b =>
                {
                    b.Navigation("Rachas");

                    b.Navigation("ReinicioContraseñas");
                });
#pragma warning restore 612, 618
        }
    }
}
